module.exports = [
    'no',
    'sí',
    'no sé',
    'puede ser',
    'no creo',
    'olvídalo',
    'qué pregunta más pndej@',
    'A',
    'pendej@',
    'pues no sé, pndej@',
    'definitivamente',
    'ni idea',
    'tal vez',
    'probablemente no',
    'sin duda',
    'es posible',
    'ni loco',
    'claro',
    'no me molestes',
    '¿en serio?',
    'sí, pero no te emociones',
    'ni en tus sueños',
    'posiblemente',
    'no cuentes con ello',
    'sin comentarios',
    'ni en broma',
    'quizás',
    'no me importa',
    'mejor pregúntale a otro',
    'claro que no',
    'por supuesto que sí',
    'absolutamente',
    'negativo',
    'puede que sí',
    'jamás',
    'eso nunca',
    'obvio',
    'lo dudo mucho',
    'por supuesto',
    'imposible',
    'quizá sí, quizá no',
    'depende',
    'ni pensarlo',
    'sí, pero no hoy',
    'nunca digas nunca',
    'es complicado',
    'estás soñando',
    'sin lugar a dudas',
    'dudoso',
    'posiblemente no',
    '¿y tú qué crees?',
    '¿por qué preguntas eso?',
    'tal vez sí',
    'no estoy seguro',
    'no tengo ni idea',
    'seguramente no',
    'seguramente sí',
    'es probable',
    'no es probable',
    'en absoluto',
    'es un secreto',
    'no quiero responder',
    'quizás algún día',
    'no cuentes con ello',
    'sí, pero con condiciones'
];